### ISSUE TITLE
device permission error

### ISSUE THREAD

**Issue by twochannel** [aneisch/rtl_433_mqtt#1]
Hello,

Host os is ubuntu 19.10 running on an x64 platform. I've run other docker containers with usb sticks passed through without issue. (those were stopped for this testing)

I'm trying to use your docker image with my rtl-sdr dongle but getting this error
```
Attaching to rtl433
rtl433    | rtl_433 version 20.02-20-g0e355dc branch master at 202003281909 inputs file rtl_tcp RTL-SDR
rtl433    | Use -h for usage help and see https://triq.org/ for documentation.
rtl433    | Trying conf file at "rtl_433.conf"...
rtl433    | Trying conf file at "/home/rtl_433/.config/rtl_433/rtl_433.conf"...
rtl433    | Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
rtl433    | Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl433    | Publishing MQTT data to 10.0.1.22 port 1883
rtl433    | Publishing events info to MQTT topic "sensor/thermopro".
rtl433    | Registered 1 out of 150 device decoding protocols [ 97 ]
rtl433    | usb_open error -3
rtl433    | Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
rtl433 exited with code 1
```
I am using your provided docker-compose.yml with updated device path for my system.

I pulled the rules file from the sdr repo and used a volume to map it from the host system to the container but still no luck. e.g.           
```yml
- /host/path/rtl-sdr.rules:/etc/udev/rules.d/20.rtlsdr.rules
```
any ideas?

**Comment by twochannel** [comment]
I think I was a bit confused above.  The udev rules should be on the host os, so I made that change. I also blacklisted the modules that could interfere with the sdr use of the dongle.  Still same error but I think I'm back on track.

**Comment by aneisch** [comment]
You are correct, the rules should be on the host. 

How are you mapping the dongle? I assume you've used a symlink as I did in my docker-compose file. Do you mind sharing that mapping? Are you using a 99-usb-serial.rules file to define the symlink path, etc?

Here is mine:
```
cat /etc/udev/rules.d/99-usb-serial.rules 
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", ATTRS{serial}=="00000001", SYMLINK+="rtl_sdr_grill", MODE="0666"
```

You can see that I'm setting thew symlink, but also setting the file mode to allow anyone to r/w the dongle.

**Comment by twochannel** [comment]
Thanks for the reply.

After reading a bit I modified the rules file from the sdr repo changing mode from 0660 to 0666 and adding the symlink but still no go.  (When i was testing before the symlink my docker mapping was changed to match) I've tried a few variations too using  the whole /dev/bus/usb, etc)

I've rebooted after each rules changes to be certain.

The symlink is getting created, i see it in /dev


```
/etc/udev/rules.d/20.rtl-sdr.rules 
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", ENV{ID_SOFTWARE_RADIO}="1", MODE="0666", GROUP="plugdev",SYMLINK+="rtl_sdr"
```
my docker mapping is (running as root w/ sudo)
```
        devices:
          - '/dev/rtl_sdr:/dev/bus/usb/002/002'
```

I confirmed my device is at that location w/ lsusb

```
Bus 002 Device 002: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

I'll try mimicking your rules file exactly and see.

**Comment by aneisch** [comment]
You might not find success with my exact rules file. I believe I've changed the Serial on my dongle so I could have multiple running. You'd want to remove the `ATTRS{serial}=="00000001",` part. 

Can you show the file permissions of the dongle itself?

```
ls -la /dev/$(readlink /dev/rtl_sdr)
crw-rw-rw- 1 root root 189, 258 Apr 11 14:02 /dev/bus/usb/003/003
```
I had problems when I first made this go where the device permissions were being overwritten. You should expect to see `crw-rw-rw-` as above.

**Comment by twochannel** [comment]
huzzah
```Attaching to rtl433
rtl433    | rtl_433 version 20.02-20-g0e355dc branch master at 202003281909 inputs file rtl_tcp RTL-SDR
rtl433    | Use -h for usage help and see https://triq.org/ for documentation.
rtl433    | Trying conf file at "rtl_433.conf"...
rtl433    | Trying conf file at "/home/rtl_433/.config/rtl_433/rtl_433.conf"...
rtl433    | Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
rtl433    | Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl433    | Publishing MQTT data to 10.0.1.22 port 1883
rtl433    | Publishing events info to MQTT topic "sensor/thermopro".
rtl433    | Registered 1 out of 150 device decoding protocols [ 97 ]
rtl433    | Found Rafael Micro R820T tuner
rtl433    | Exact sample rate is: 250000.000414 Hz
rtl433    | [R82XX] PLL not locked!
rtl433    | Sample rate set to 250000 S/s.
rtl433    | Tuner gain set to Auto.
rtl433    | Tuned to 433.920MHz.
```
this was w/ your rule as-is.    

To answer your reply
```
crw-rw-rw- 1 root plugdev 189, 129 Apr 18 15:34 /dev/bus/usb/002/002
```
do you you run multiple sdrs to handle diff frequencies?  I was wondering if I can do some frequency hopping to avoid that to support the grill and other frequencies.

**Comment by aneisch** [comment]
Great! Glad it's now working for you! You can see my other repo for [train-sensor](https://github.com/aneisch/train-sensor). I run this container 24/7 to detect passing trains. I only use the rtl_433 container when I am grilling or cooking something. 

The devices both have the same idVendor and idProduct, but I was able to modify the serial on one using [rtl_eeprom](http://manpages.ubuntu.com/manpages/trusty/man1/rtl_eeprom.1.html) so that they could be distinguished.

**Comment by twochannel** [comment]
Thank you again! 
I'm using this w/ a Maverick ET-72 but my luck, the units are getting published as Celsius :/. It looks like rtl_433 has a -C option to change this to 'customary'  which I'm assuming is Fahrenheit.  Any suggestions how best to use this?  

And that is very cool! I will check out the train stuff, i had no idea.  What do you do w/ the train data?

**Comment by aneisch** [comment]
I actually had no idea about the units selection. I just pushed a change that sets a default of `native` units and allows for override with the environment variable `UNITS`. You can use `UNITS=customary` to output Fahrenheit. Docker build in progress but you should be able to pull a new image ~shortly~ now.

I'm not doing anything interesting with the train data, I was just curious how many passed through each day :)

![Screen Shot 2020-04-18 at 3 28 03 PM](https://user-images.githubusercontent.com/6991461/79670516-4f59a880-8189-11ea-9c33-9aa8a2427d3d.png)

**Comment by twochannel** [comment]
wow thank you.

but i dont seem to be getting any data published to mqtt now, either with specifying the units env variable in the docker-compose or not.

**Comment by aneisch** [comment]
Hmm.. perhaps your device can't covert or use the -C flag for whatever reason. 

You can use this command to run the container interactively to see what's being output:
`docker run -it --rm --device '/dev/rtl_sdr::/dev/bus/usb/002/002' aneisch/rtl_433_mqtt rtl_433 -C customary`. You can modify this command to change the flags, etc.

**Comment by twochannel** [comment]
All is good, I was not patient enough, sorry for the false report.

Thank you again for all the help and the update.
